openapi: 3.0.0
info:
    title: FX Rate Sample API Specification
    version: 1.0.0
servers:
    - url: https://ms-fx-rates.apps.dev.ocbc.com
      description: Local server
paths:
    /mx-fx-rates/v1/fxRates:
        get:
            tags:
                - fx-controller
            operationId: getFxRates
            parameters:
                - name: x-request-id
                  in: header
                  required: true
                  schema:
                    type: string
                - name: x-requestor-id
                  in: header
                  required: true
                  schema:
                    type: string
                - name: x-acc-jwt
                  in: header
                  required: false
                  schema:
                    type: string
                - name: fromCcy
                  in: query
                  required: false
                  schema:
                    type: string
                - name: toCcy
                  in: query
                  required: false
                  schema:
                    type: string
                - name: rateType
                  in: query
                  required: true
                  schema:
                    type: string
                - name: entityType
                  in: query
                  required: false
                  schema:
                    type: string
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: string
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiError'
                500:
                    description: Internal Server Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiError'
    /mx-fx-rates/v1/fxRates/fxRatesVersion:
        get:
            tags:
                - fx-controller
            operationId: version
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: string
                500:
                    description: Internal Server Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiError'
components:
    schemas:
        ApiError:
            type: object
            properties:
                timestamp:
                    type: string
                message:
                    type: string
                debugMessage:
                    type: string
                code:
                    type: integer
                errors:
                    type: array
                    items:
                        $ref: '#/components/schemas/ApiSubError'                                                                                                                  
        ApiSubError:
            type: object
            properties:
                resourceName:
                    type: string
                field:
                    type: string
                rejectedValue:
                    type: string
                message:
                    type: integer
                